### ISSUE TITLE
mercury-hlctrail-dev has some conflicts with mercury-hlcpar-dev

### ISSUE THREAD

**Issue by NadiaYvette** [Mercury-Language/packaging#3]
$ sudo apt-get -fu install `sudo apt-cache showsrc mercury|grep '^ mercury'|awk '{print $1}'`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
mercury-devel is already the newest version (14.01.1-3).
mercury-docs is already the newest version (14.01.1-3).
mercury-examples is already the newest version (14.01.1-3).
mercury-gc is already the newest version (14.01.1-3).
mercury-gc-dev is already the newest version (14.01.1-3).
mercury-hlc is already the newest version (14.01.1-3).
mercury-hlc-dev is already the newest version (14.01.1-3).
mercury-hlcpar is already the newest version (14.01.1-3).
mercury-hlcpar-dev is already the newest version (14.01.1-3).
mercury-hlctrail is already the newest version (14.01.1-3).
mercury-llc is already the newest version (14.01.1-3).
mercury-llc-dev is already the newest version (14.01.1-3).
mercury-llcpar is already the newest version (14.01.1-3).
mercury-llcpar-dev is already the newest version (14.01.1-3).
mercury-llctrail is already the newest version (14.01.1-3).
mercury-llctrail-dev is already the newest version (14.01.1-3).
mercury-maintainers is already the newest version (14.01.1-3).
mercury-recommended is already the newest version (14.01.1-3).
mercury-tools is already the newest version (14.01.1-3).
The following NEW packages will be installed:
  mercury-hlctrail-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/1,767 kB of archives.
After this operation, 18.5 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
(Reading database ... 277361 files and directories currently installed.)
Preparing to unpack .../mercury-hlctrail-dev_14.01.1-3_amd64.deb ...
Unpacking mercury-hlctrail-dev (14.01.1-3) ...
dpkg: error processing archive /var/cache/apt/archives/mercury-hlctrail-dev_14.01.1-3_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/mercury/modules/hlc.par.gc/mer_browser.init', which is also in package mercury-hlcpar-dev 14.01.1-3
Errors were encountered while processing:
 /var/cache/apt/archives/mercury-hlctrail-dev_14.01.1-3_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
$ sudo apt-get -fu --force-overwrite mercury-hlctrail-dev
E: Command line option 'f' [from -fu] is not understood in combination with the other options.
$ sudo apt-get -fu --force-overwrite install mercury-hlctrail-dev
E: Command line option --force-overwrite is not understood in combination with the other options
$ sudo apt-get --force-overwrite install mercury-hlctrail-dev    
E: Command line option --force-overwrite is not understood in combination with the other options
$ sudo apt-get --download-only install mercury-hlctrail-dev 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  mercury-hlctrail-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/1,767 kB of archives.
After this operation, 18.5 MB of additional disk space will be used.
Download complete and in download only mode
$ sudo dpkg -i /var/cache/apt/archives/mercury-hlctrail-dev_14.01.1-3_amd64.deb
(Reading database ... 277361 files and directories currently installed.)
Preparing to unpack .../mercury-hlctrail-dev_14.01.1-3_amd64.deb ...
Unpacking mercury-hlctrail-dev (14.01.1-3) ...
dpkg: error processing archive /var/cache/apt/archives/mercury-hlctrail-dev_14.01.1-3_amd64.deb (--install):
 trying to overwrite '/usr/lib/mercury/modules/hlc.par.gc/mer_browser.init', which is also in package mercury-hlcpar-dev 14.01.1-3
Errors were encountered while processing:
 /var/cache/apt/archives/mercury-hlctrail-dev_14.01.1-3_amd64.deb
$ sudo dpkg --force-overwrite -i /var/cache/apt/archives/mercury-hlctrail-dev_14.01.1-3_amd64.deb
(Reading database ... 277361 files and directories currently installed.)
Preparing to unpack .../mercury-hlctrail-dev_14.01.1-3_amd64.deb ...
Unpacking mercury-hlctrail-dev (14.01.1-3) ...
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mercury/modules/hlc.par.gc/mer_browser.init', which is also in package mercury-hlcpar-dev 14.01.1-3
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mercury/modules/hlc.par.gc/mer_mdbcomp.init', which is also in package mercury-hlcpar-dev 14.01.1-3
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mercury/modules/hlc.par.gc/mer_rt.init', which is also in package mercury-hlcpar-dev 14.01.1-3
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mercury/modules/hlc.par.gc/mer_ssdb.init', which is also in package mercury-hlcpar-dev 14.01.1-3
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mercury/modules/hlc.par.gc/mer_std.init', which is also in package mercury-hlcpar-dev 14.01.1-3
Setting up mercury-hlctrail-dev (14.01.1-3) ...
$

**Comment by PaulBone** [comment]
Thanks. I'll fix that in the next version, Looks like I've got a typo somewhere so it should be a simple fix.

**Comment by PaulBone** [comment]
I've fixed the issue and I'm building new packages now.  Packages for 14.01.1-4 built for stretch are already online.  Thanks for reporting this @NadiaYvette
