### ISSUE TITLE
Packaging for Ubuntu 19.04?

### ISSUE THREAD

**Issue by vmchale** [Mercury-Language/packaging#4]
I am using Ubuntu 19.04 and would ideally like to get my packages from a `disco` ppa. Right now it only has `stretch` :)

**Comment by PaulBone** [comment]
Do the existing packages work or are they broken in some way?

What I've found is that as Mercury has a small number of dependencies sometimes one package works on multiple versions. If it doesn't work I'm happy to build a new package, but knowing that would help me prioritise it (and know what to look for when I try to make a new package).

Thank you.

**Comment by PaulBrownMagic** [comment]
I'm on disco too, when I try to apt install from jessie I'm getting errors:

```
:~$ sudo apt install mercury-devel mercury-tools mercury-recommended

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 mercury-devel : Depends: libreadline6 (>= 6.0) but it is not installable
 mercury-tools : Depends: gcc-4.8 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by PaulBone** [comment]
I'll work on this this evening. Thanks for the reminder.

**Comment by PaulBone** [comment]
Here's what I'm working on to update the packages.

- [x] Update pbuilder and reprepro configuration to support new distro versions, testing first with debian-buster. If buster doesn't work then I'll add an ubuntu-disco specific configuration also.
- [x] Modify repository structure. The master branch is now lagacy and rotd is now master. (14.01 is too old, I'll focus on mercury-rotd packages instead.)
- [ ] Parallelise builds so I don't have to wait so long.
- [ ] Write scripts w/ templates for filling in version number, base grade and 
     package name, and repo name into the `debian/control` and maybe `debian/changelog` files.
- [ ] Bump version number for buster.
- [ ] Write rsync scripts.
- [ ] Test buster packages, on buster but also on disco.
- [ ] Update HTML page.

**Comment by PaulBone** [comment]
I have added new package builds for both "buster" (Debian 10) and "disco" (Ubuntu 19.04). I only intend to package mercury-rotd on these unless there's a new Mercury release. The Mercury version packaged is ROTD 2018-11-14, same as was already done for the other OSs.  I'll update this in a couple of weeks.

Follow the instructions at http://dl.mercurylang.org/deb/ and let me know if there are any problems. Enjoy.
